# Generated by Django 4.2.1 on 2023-05-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_variation_variation_category_reviewrating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("color", "color"), ("size", "size")], max_length=200
            ),
        ),
    ]
